In [8]:
import pandas as pd

In [9]:
path = '/datos_rrss.xlsx'

In [10]:
pd.read_excel (path)

      Nombre  Cantidad  ES_FBK   Año
0   Facebook      2449    True  2006
1    Twitter       339   False  2006
2  Instagram      1000    True  2010
3    YouTube      2000   False  2005
4   LinkedIn       663   False  2003
5   WhatsApp      1600    True  2009

In [11]:
pd.read_excel(path,
              sheet_name='Hoja2')

      Nombre  Cantidad  ES_FBK   Año
0   Facebook      2449    True  2006
1    Twitter       339   False  2006
2  Instagram      1000    True  2010

In [16]:
pd.read_excel(path,
              sheet_name='Hoja3',
              header=None,
              names=['col1', 'col2','col3', 'col4'])

        col1  col2   col3  col4
0   Facebook  2449   True  2006
1    Twitter   339  False  2006
2  Instagram  1000   True  2010
3    YouTube  2000  False  2005
4   LinkedIn   663  False  2003
5   WhatsApp  1600   True  2009

In [15]:
pd.read_excel(path,
              sheet_name='Hoja3',
              header=None,
              names=['Nombre', 'Cantidad','ES_FBK', 'Año'])

      Nombre  Cantidad  ES_FBK   Año
0   Facebook      2449    True  2006
1    Twitter       339   False  2006
2  Instagram      1000    True  2010
3    YouTube      2000   False  2005
4   LinkedIn       663   False  2003
5   WhatsApp      1600    True  2009