In [1]:
import pandas as pd

In [4]:
pd.read_csv('/content/Practica08_csvtopd/datos_rrss_t1(1).csv')

      Nombre  Cantidad     ES_FBK  Anio
0   Facebook      2449  VERDADERO  2006
1    Twitter       339      FALSO  2006
2  Instagram      1000  VERDADERO  2010
3    YouTube      2000      FALSO  2005
4   LinkedIn       663      FALSO  2003
5   WhatsApp      1600  VERDADERO  2009

In [9]:
pd.read_csv('/content/Practica08_csvtopd/datos_rrss_t2(1).csv',sep= ';')

      Nombre  Cantidad     ES_FBK  Anio
0   Facebook      2449  VERDADERO  2006
1    Twitter       339      FALSO  2006
2  Instagram      1000  VERDADERO  2010

In [6]:
pd.read_csv('/content/Practica08_csvtopd/datos_rrss_t3(1).csv')

    Facebook  2449  VERDADERO  2006
0    Twitter   339      FALSO  2006
1  Instagram  1000  VERDADERO  2010
2    YouTube  2000      FALSO  2005
3   LinkedIn   663      FALSO  2003
4   WhatsApp  1600  VERDADERO  2009

In [12]:
pd.read_csv('/content/Practica08_csvtopd/datos_rrss_t3(1).csv',
              header=None,
              names=['Nombre', 'Cantidad','ES_FBK', 'Año'])

      Nombre  Cantidad     ES_FBK   Año
0   Facebook      2449  VERDADERO  2006
1    Twitter       339      FALSO  2006
2  Instagram      1000  VERDADERO  2010
3    YouTube      2000      FALSO  2005
4   LinkedIn       663      FALSO  2003
5   WhatsApp      1600  VERDADERO  2009

In [13]:
pd.read_csv('/content/Practica08_csvtopd/datos_rrss_t3(1).csv',
              header=None,
              names=['col1', 'col2','col3', 'col4'])

        col1  col2       col3  col4
0   Facebook  2449  VERDADERO  2006
1    Twitter   339      FALSO  2006
2  Instagram  1000  VERDADERO  2010
3    YouTube  2000      FALSO  2005
4   LinkedIn   663      FALSO  2003
5   WhatsApp  1600  VERDADERO  2009